### ISSUE TITLE
TinyMCE content window expanding all on it's own

### ISSUE THREAD

**Issue by kevince52** [tsquez/wp-forge#35] opened 2015-03-08 23:06 UTC
Hi,

I'm playing with your theme and it seems to be working great. I am running into one issue that's more of a nuisance than a real problem. The content window expands all on it's own. Every time I open a page to edit it. The TinyMCE window slowly expands to fill the height. Or if I click in the window it adds one line. I've tried multiple browsers and same issue. I've switched themes and problem goes away. Again not a super pressing issue but any idea what might be happening? I tired looking around but I only get info about customizing TinyMCE. Nothing helpful.

Great theme BTW. I'm a huge fan of Foundation and not many WP starters out there. Certainly not as good as this one.

Cheers!

**Comment by tsquez** [comment] 2015-03-09 01:02
Hey there,

Glad you like the theme and yes what you have described has been brought to my attention before. It has something to do with foundation.css - I have to apologize that I have know about this for a while and have been meaning to ask the kind folks over at foundation if they can figure out what it is.

You can "turn this off" but going into a post and in the upper right hand corner click on "screen Options". When the screen comes sliding down you will see this:

Enable full-height editor and distraction-free functionality.

Uncheck this box and the issue should go away. I will ask Foundation and see if they can figure out what it is.

Again my apologies. Hope this helps.

**Comment by kevince52** [comment] 2015-03-09 11:52
Thanks Thomas. Should have thought of that. :)

So I did and noticed another little oddity. The first time I save a page
the Page Attributes panel disappears. I have to go back and re-enable it in
screen options. Not sure if these 2 things are related but again it does
not happen with other themes. Including another Foundation theme I'm using.
(Flotsome from ThemeForest.)

Maybe something to do with the CSS you've added in Tiny MCE?



*Kevin Cunningham*
kevincunningham@gmail.com
902-448-2836

**Comment by kevince52** [comment] 2015-03-09 11:54
Sorry. Correction to my last message. Every time I *change* templates the
Page Attributes panel disappears.



*Kevin Cunningham*
kevincunningham@gmail.com
902-448-2836

**Comment by tsquez** [comment] 2015-03-09 11:56
What do you mean change templates?

**Comment by tsquez** [comment] 2015-03-09 12:06
I have never had the page attributes section disappear and I have never had anyone say that is does after changing templates. WP-Forge has been downloaded over 8k times and used on many, many sites and no one has ever stated anything like that. Also WP-Forge was recently approved to be included in the theme directory on WordPress.org and none of the reviewers mentioned anything like that happening.

**Comment by kevince52** [comment] 2015-03-09 12:07
In Page Attributes I select a new template. Instead of "Default Template" I
choose either one of yours, Front Page or Full width or I choose one I have
created. Same thing happens when I flip back to Default.

https://www.dropbox.com/s/zoiy9615hxr0m08/Screenshot%202015-03-09%2009.06.54.png?dl=0



*Kevin Cunningham*
kevincunningham@gmail.com
902-448-2836

**Comment by tsquez** [comment] 2015-03-09 12:11
Sorry but I have just tested this in different browsers and that is not happening. I eve tested on a demo server in different browsers and that isn't happening so I can't reproduce what you are experiencing.

**Comment by tsquez** [comment] 2015-03-09 12:18
Sorry forgot to ask, can you disable any and all plugins you may have and see if what you are experiencing happens.

**Comment by kevince52** [comment] 2015-03-09 12:31
Looks like it's Advanced Custom Fields causing the conflict. All plugins
off, all okay. ACF active, odd behaviour.



*Kevin Cunningham*
kevincunningham@gmail.com
902-448-2836

**Comment by kevince52** [comment] 2015-03-09 12:32
I've got a screen cast if you want to see.



*Kevin Cunningham*
kevincunningham@gmail.com
902-448-2836

**Comment by tsquez** [comment] 2015-03-09 12:38
Yes please post it. If anyone runs into the same issue we can point them here. Thanks again.

**Comment by tsquez** [comment] 2015-03-14 15:12
Hi Kevin,

Seems like we got the issue resolved here https://github.com/zurb/foundation/issues/6380. As you can see @veraxus provided a fix based on his own experience. If you would like, you can open up style.css and look for the following (on or around line 1033):

```
html .mceContentBody {
	max-width: 920px;
	margin:15px 0 0 15px;
	padding:0;
	background:#fff;
}
```
and change it to this:
```
body, html {
	height: auto !important;
}
html {
    padding:15px !important;
}
html .mceContentBody {
	padding:0;
	background:#fff;
}
```
This has already been added to the new version of WP-Forge (not for 5.5.1.7 which is waiting on final approval but for 5.5.1.8 which I will submit once WP-Forge goes live on WordPress.org).

I will go ahead and close this issue as fixed. Hope this helps :sunglasses:

**Closed by tsquez** 2015-03-14 15:12 UTC
Labels: Bug!
